### PR TITLE
Copybara sync for ScrollablePositionedList 0.1.3

### PR DESCRIPTION
**Pull request by jamesderlin**

### CODE REVIEW

**Comment by vasilich6107** [comment]
@jamesderlin @mehmetf could you give some information about the release schedule?
As far as see the 0.1.3 version PR was merged into master.

**Comment by jamesderlin** [comment]
@vasilich6107 We haven't published a release to `pub.dev` yet because there are some administrative issues that we need to address first.  Hopefully they will be resolved within the week, but I can't make any promises.

**Comment by mehmetf** [comment]
0.1.3 has been released.

**Comment by mehmetf** [comment]
@jamesderlin, I am a member of flutter.dev publisher so if you want to publish something let me know until we figure out the google.dev issue.

**Pull request merged**
