### PR TITLE
Pull beta branch instead of master

### PR DESCRIPTION
**Pull request by mehmetf**

### CODE REVIEW

**Comment by jamesderlin** [comment]
I'm hesitant to change this since:
* It's caused by https://github.com/flutter/flutter/issues/53688, which is a TODAY issue.
* It will make it harder for us to keep our internal repository (which must track breaking changes in `master`) in sync with the GitHub repo.

If we do still want to track `beta`, then `--depth=1` should be added to the `git clone` command, and the `git fetch --deepen=1` command can be removed.

**Comment by mehmetf** [comment]
> It will make it harder for us to keep our internal repository (which must track breaking changes in master) in sync with the GitHub repo.

That would be a tough situation regardless. I don't know of a good way to communicate to users that the package now requires `master` channel of Flutter. I don't think pub understands these channels, so what kind of pubspec.yaml change would we do?

I would rather try to depend on the most common Flutter branch that allows people to use these packages. Beta seems to be a reasonable choice though I don't have any metrics to prove this.

Our g3 -> gh sync will be blocked by failing tests on beta. Right now, they will just pass even if we forget to update min required version which would then be a surprise to users trying to update the package.

Ideally, we should be able to pin both the pubspec.yaml files and the test env to the same flutter version.

**Comment by jamesderlin** [comment]
> That would be a tough situation regardless. I don't know of a good way to communicate to users that the package now requires master channel of Flutter. I don't think pub understands these channels, so what kind of pubspec.yaml change would we do?

Our existing practice is to publish an `x.y.z-dev` release (or just leave the change on GitHub and not publish to `pub.dev`).

**Comment by mehmetf** [comment]
> Our existing practice is to publish an x.y.z-dev release (or just leave the change on GitHub and not publish to pub.dev).

I don't have a good solution for this. What you are describing is a manual process that can go wrong easily. Basically, we need to remember that we fixed a breaking change due to master and not publish it until that change is pushed to Flutter dev.

I feel that it is better *not* sync this package to github until that change is published to Flutter dev. At least, there is no way to accidentally publish it and we can make it mechanical. That is, update pubspec.yaml *and* test env for the tests to pass.

Of course the downside is that GH copy will be stale and people won't be able to submit meaningful PRs. I don't think that's a big deal given this is being mastered in google3.

WDYT? More importantly, wdyt of my pin flutter version and pubspec deps version to the same flutter version idea?

**Comment by jamesderlin** [comment]
> I would rather try to depend on the most common Flutter branch that allows people to use these packages. Beta seems to be a reasonable choice though I don't have any metrics to prove this.

If our GitHub repo tracks Flutter `beta`, then any downstream consumers who are tracking Flutter `master` will be broken by breaking changes between `beta` and `master` and will have little recourse other than to switch Flutter channels. (I acknowledge that those consumers essentially are inviting that kind of trouble, however.)

If our repo tracks Flutter `master`, we instead might break downstream consumers who are tracking Flutter `beta`.  However, I think that *usually* should be much easier for consumers to handle.  If there's a single breakage between Flutter `stable` and `master`, a consumer tracking Flutter `beta` could use either the non-dev package (if the breakage occurred after `beta`) or could use the dev package (if the breakage occurred before `beta`).  There would need to be *two* breakages to break a consumer tracking Flutter `beta` in this scenario.

> Basically, we need to remember that we fixed a breaking change due to master and not publish it until that change is pushed to Flutter dev.

I'm not sure what you mean.  If there's a breaking change on Flutter `master`, then we sync and push a `x.y.z-dev` release of the package and are done.  Regardless of whether the flutter.widgets repo tracks Flutter `beta` or `master`, breaking changes not in Flutter `stable` will warrant a `-dev` release of flutter.widgets.  Someone will need to keep track of when Flutter's `stable` branch is updated so that the `-dev` release can be published as non-dev either way.

There is a chance that a fix for a breaking change will be made to a package *without* updating the version to `-dev`, and that would be a problem.  We probably could address that with instructions for rollers or presubmit checks.

> WDYT? More importantly, wdyt of my pin flutter version and pubspec deps version to the same flutter version idea?

I agree that it's a problem that the minimum version can very easily become wrong and that it would be great if the travis presubmit tests used the Flutter version specified by `pubspec.yaml`. (More generally, it'd be nice for other packages too. I'm not sure if there's a way to get `pub get` to lock package versions to the minimum specified versions; maybe we should file a feature request for this scenario?)

**Comment by mehmetf** [comment]
We should table this for now. Let's keep it pinned to beta until the time comes where a breaking change forces us to move to master. We can also do it after the TODAY issue is fixed.

For my edification:
> If there's a breaking change on Flutter master, then we sync and push a x.y.z-dev release of the package and are done.

If we release a dev package, what does its pubspec contain in terms of flutter version? I would assume something like ^1.1.12. So, how do consumers that are picking up a dev version know they are supposed to track master in order to not break their build?

**Comment by jamesderlin** [comment]
> If we release a dev package, what does its pubspec contain in terms of flutter version? I would assume something like ^1.1.12. So, how do consumers that are picking up a dev version know they are supposed to track master in order to not break their build?

You're right, it would have to have to be the latest Flutter `dev` release, so not exactly `master`.

**Comment by jamesderlin** [comment]
Although in practice, Flutter `master` and Flutter `dev` *usually* should be the same for our purposes: with the internal Google repo as the source of truth, we'd fix breakage only in response to an incoming Flutter roll (from `master`), and assuming everything is successful, the roll point should become the next `dev` release.

**Comment by christopherfujino** [comment]
FYI the TODAY issue was resolved in https://github.com/flutter/flutter/pull/53715

**Pull request merged**
