### PR TITLE
feature: support for shrinkWrap

### PR DESCRIPTION
**Pull request by lvfen**
## Description

support for shrinkWrap for scrollPositionList， fix the shrinkWrap make scroll error.

## Related Issues

fix issue: #52
[ScrollablePositionedList: Provide shrinkWrap](https://github.com/google/flutter.widgets/issues/52)

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I signed the [CLA].
- [x] All tests from running `flutter test` pass.
- [x] `flutter analyze` does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

[CLA]: https://cla.developers.google.com/

### CODE REVIEW

**Comment by lvfen** [comment]
why failed?

**Comment by lvfen** [comment]
why the ci always error?
flutter test and flutter analyze has pass on local.

**Comment by jamesderlin** [comment]
CI failed because you need to run `dart format` on your code first.

**Comment by lvfen** [comment]
> If you look at the CI details, it says:
> 
> > Formatting failed: 1
> 
> CI failed because you need to run `dart format` on your code first.

Now I have run flutter format for all file, why failed again?
`flutter format packages                                                                                                                                            longquan@LUCIOLONG-MC0
Formatting directory packages:
Unchanged flutter_simple_treeview/example/lib/main.dart
Unchanged flutter_simple_treeview/example/lib/trees/controller_usage.dart
Unchanged flutter_simple_treeview/example/lib/trees/tree_from_json.dart
Unchanged flutter_simple_treeview/lib/flutter_simple_treeview.dart
Unchanged flutter_simple_treeview/lib/src/builder.dart
Unchanged flutter_simple_treeview/lib/src/copy_tree_nodes.dart
Unchanged flutter_simple_treeview/lib/src/node_widget.dart
Unchanged flutter_simple_treeview/lib/src/primitives/key_provider.dart
Unchanged flutter_simple_treeview/lib/src/primitives/tree_controller.dart
Unchanged flutter_simple_treeview/lib/src/primitives/tree_node.dart
Unchanged flutter_simple_treeview/lib/src/tree_view.dart
Unchanged flutter_simple_treeview/test/primitives/tree_controller_test.dart
Unchanged flutter_simple_treeview/test/tree_view_test.dart
Unchanged linked_scroll_controller/lib/linked_scroll_controller.dart
Unchanged linked_scroll_controller/test/linked_scroll_controller_test.dart
Unchanged scrollable_positioned_list/example/lib/main.dart
Unchanged scrollable_positioned_list/example/test/scrollable_positioned_list_example_test.dart
Unchanged scrollable_positioned_list/lib/scrollable_positioned_list.dart
Unchanged scrollable_positioned_list/lib/src/element_registry.dart
Unchanged scrollable_positioned_list/lib/src/item_positions_listener.dart
Unchanged scrollable_positioned_list/lib/src/item_positions_notifier.dart
Unchanged scrollable_positioned_list/lib/src/positioned_list.dart
Unchanged scrollable_positioned_list/lib/src/post_mount_callback.dart
Unchanged scrollable_positioned_list/lib/src/scroll_view.dart
Unchanged scrollable_positioned_list/lib/src/scrollable_positioned_list.dart
Unchanged scrollable_positioned_list/lib/src/viewport.dart
Unchanged scrollable_positioned_list/lib/src/wrapping.dart
Unchanged scrollable_positioned_list/test/horizontal_scrollable_positioned_list_test.dart
Unchanged scrollable_positioned_list/test/positioned_list_test.dart
Unchanged scrollable_positioned_list/test/reversed_positioned_list_test.dart
Unchanged scrollable_positioned_list/test/reversed_scrollable_positioned_list_test.dart
Unchanged scrollable_positioned_list/test/scrollable_positioned_list_test.dart
Unchanged scrollable_positioned_list/test/separated_positioned_list_test.dart
Unchanged scrollable_positioned_list/test/separated_scrollable_positioned_list_test.dart
Unchanged scrollable_positioned_list/test/seperated_horizontal_scrollable_positioned_list_test.dart
Unchanged self_storing_input/example/lib/main.dart
Unchanged self_storing_input/lib/self_storing_input.dart
Unchanged self_storing_input/lib/src/primitives/message_overlay.dart
Unchanged self_storing_input/lib/src/primitives/operation_result.dart
Unchanged self_storing_input/lib/src/primitives/overlay.dart
Unchanged self_storing_input/lib/src/primitives/overlay_builder.dart
Unchanged self_storing_input/lib/src/primitives/saver.dart
Unchanged self_storing_input/lib/src/primitives/the_progress_indicator.dart
Unchanged self_storing_input/lib/src/self_storing_checkbox.dart
Unchanged self_storing_input/lib/src/self_storing_checkbox/custom_checkbox.dart
Unchanged self_storing_input/lib/src/self_storing_checkbox/self_storing_checkbox_style.dart
Unchanged self_storing_input/lib/src/self_storing_checkbox/shared_state.dart
Unchanged self_storing_input/lib/src/self_storing_radio_group.dart
Unchanged self_storing_input/lib/src/self_storing_radio_group/custom_radio.dart
Unchanged self_storing_input/lib/src/self_storing_radio_group/self_storing_radio_group_style.dart
Unchanged self_storing_input/lib/src/self_storing_radio_group/shared_state.dart
Unchanged self_storing_input/lib/src/self_storing_text.dart
Unchanged self_storing_input/lib/src/self_storing_text/edit_button.dart
Unchanged self_storing_input/lib/src/self_storing_text/overlay_box.dart
Unchanged self_storing_input/lib/src/self_storing_text/self_storing_text_style.dart
Unchanged self_storing_input/lib/src/self_storing_text/shared_state.dart
Unchanged self_storing_input/test/primitives/message_overlay_test.dart
Unchanged self_storing_input/test/self_storing_checkbox_test.dart
Unchanged self_storing_input/test/self_storing_text_test.dart
Unchanged self_storing_input/test/testing/widget_testing.dart
Unchanged visibility_detector/example/lib/main.dart
Unchanged visibility_detector/example/test/unit_test.dart
Unchanged visibility_detector/lib/src/render_sliver_visibility_detector.dart
Unchanged visibility_detector/lib/src/render_visibility_detector.dart
Unchanged visibility_detector/lib/src/visibility_detector.dart
Unchanged visibility_detector/lib/src/visibility_detector_controller.dart
Unchanged visibility_detector/lib/src/visibility_detector_layer.dart
Unchanged visibility_detector/lib/visibility_detector.dart
Unchanged visibility_detector/test/text_handle_test.dart
Unchanged visibility_detector/test/unit_test.dart
Unchanged visibility_detector/test/widget_test.dart
`

**Comment by jamesderlin** [comment]
> The log always says:
> 
> > Formatting failed: 1
> 
> But not tips which code failed.

It tells you exactly which:

> ```
> $ ./tool/travis.sh
> Checking formatting...
> visibility_detector/example/lib/main.dart
> visibility_detector/lib/src/render_sliver_visibility_detector.dart
> visibility_detector/lib/src/render_visibility_detector.dart
> visibility_detector/lib/src/visibility_detector.dart
> Formatting failed: 1
> ```

CI is using `flutter format` from the `beta` branch, which uses a newer version of `dart format` (that fixes https://github.com/dart-lang/dart_style/issues/1010) than what you probably are using. (Sorry that CI is complaining about files that you didn't touch.)

**Comment by jamesderlin** [comment]
The formatting issues with the existing code should be fixed now (48cd258c7d99d12651f8cacb1634f83c166c3bea).  Sorry about that.

**Comment by lvfen** [comment]
> The formatting issues with the existing code should be fixed now ([48cd258](https://github.com/google/flutter.widgets/commit/48cd258c7d99d12651f8cacb1634f83c166c3bea)). Sorry about that.



> The formatting issues with the existing code should be fixed now ([48cd258](https://github.com/google/flutter.widgets/commit/48cd258c7d99d12651f8cacb1634f83c166c3bea)). Sorry about that.

OK，I have merge master and push again.

**Comment by tarobins** [comment]
@lvfen do you have some tests for this change?  Or could you describe some that I could maybe write?

**Comment by lvfen** [comment]
> Thanks for the PR!!
> 
> @lvfen do you have some tests for this change? Or could you describe some that I could maybe write?

This is my simple test code:
```

final int itemCount = 100;
final int jumpIndex = 10;

Widget scrollWidget() {
    return Column(children: [
      FlatButton(
          onPressed: () {
            _scrollController.scrollTo(jumpIndex: 10, alignment: 1.0, duration: Duration(milliseconds: 20));
          },
          child: Text('jump to Item')),
      Expanded(
          child: ScrollablePositionedList.builder(
        itemScrollController: _scrollController,
        itemPositionsListener: _positionsListener,
        reverse: true,
        shrinkWrap: true,
        itemBuilder: (context, index) {
          return ScrollItem(index);
        },
        itemCount: itemCount,
      )),
    ]);
  }

  Widget scrollItem(int index) {
    return ScrollItem(index);
  }

......

class ScrollItem extends StatelessWidget {
  final int index;

  const ScrollItem(this.index);

  @override
  Widget build(BuildContext context) {
    return Container(
        margin: EdgeInsets.all(20),
        color: Colors.blueGrey,
        height: 50,
        alignment: Alignment.center,
        child: Text("The $index item.",
            style: TextStyle(color: Colors.redAccent, fontSize: 20)));
  }
}
```

When the shrinkWrap is not supported, we changed item count to a small num, eg. 1, then we see that the list is from bottom to the top, which not meet our expectations. 
image

So  we need shrinkWrap to make the list wrap for the items. And now the list can layout from the top to the bottom because of the shrinkWrap support.
image

**Comment by buraktabn** [comment]
I created a test repo for testing my use case. I need to use `ScrollablePositionedList` inside a `ListView`. That's why I needed `shrinkWrap` property.

https://github.com/buraktabn/scrollable_positioned_list_test/blob/main/lib/main.dart#L43-L59

<details>
  <summary>flutter doctor - v</summary>
  
```
burak@burak:~/github/scrollable_positioned_list_test$ flutter doctor -v
[✓] Flutter (Channel stable, 2.0.1, on Linux, locale en_CA.UTF-8)
    • Flutter version 2.0.1 at /home/burak/_tools/flutter
    • Framework revision c5a4b4029c (9 weeks ago), 2021-03-04 09:47:48 -0800
    • Engine revision 40441def69
    • Dart version 2.12.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /home/burak/Android/Sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /home/burak/_tools/jdk1.8.0_271/bin/java
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_271-b09)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[✓] Connected device (2 available)
    • Pixel 3 XL (mobile) • 8BNY11AAM • android-arm64  • Android 11 (API 30)
    • Chrome (web)        • chrome    • web-javascript • Google Chrome 90.0.4430.85

! Doctor found issues in 1 category.
```
</details>

```
════════ Exception caught by rendering library ═════════════════════════════════
The following assertion was thrown during performLayout():
'package:flutter/src/rendering/viewport.dart': Failed assertion: line 490 pos 12: 'scrollOffset.isFinite': is not true.

The relevant error-causing widget was
CustomShrinkWrappingViewport
../…/src/scroll_view.dart:65
When the exception was thrown, this was the stack
#2      RenderViewportBase.layoutChildSequence
package:flutter/…/rendering/viewport.dart:490
#3      CustomRenderShrinkWrappingViewport._attemptLayout
package:scrollable_positioned_list/src/wrapping.dart:322
#4      CustomRenderShrinkWrappingViewport.performLayout
package:scrollable_positioned_list/src/wrapping.dart:222
#5      RenderObject.layout
package:flutter/…/rendering/object.dart:1784
#6      RenderProxyBoxMixin.performLayout
package:flutter/…/rendering/proxy_box.dart:118
```

**Comment by jamesderlin** [comment]
When we asks for tests, we mean that you need to add automated test cases to the package's existing `test/` directory so that they will be automatically run and verified when by `flutter test`.  This is important to avoid regressions.

**Comment by lvfen** [comment]
> When we asks for tests, we mean that you need to add automated test cases to the package's existing `test/` directory so that they will be automatically run and verified when by `flutter test`. This is important to avoid regressions.

I know that，I will write the test case later.

**Comment by AcodeWang** [comment]
Is there any update for this PR merge ?

**Comment by danieeelfc** [comment]
Great, thanks for your work with shrinkWrap!

**Comment by FirstJavaMaster** [comment]
no offense, I can't use shrinkWrap configuration in 0.2.0-nullsafety.0 version, so when can I use it?

**Comment by lvfen** [comment]
> Thanks for the PR!!
> 
> @lvfen do you have some tests for this change? Or could you describe some that I could maybe write?

I have write some te

**Comment by khanhtruongq** [comment]
please review it

**Review by tarobins — APPROVED** [review]

**Pull request merged**
